# Project-wide Gradle settings.

# Parámetros de memoria del sistema y codificación
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Activación obligatoria de AndroidX para Firebase y Material Components
android.useAndroidX=true

# Desactivamos Jetifier porque tus librerías ya están actualizadas en AndroidX (Quita el Error 4)
android.enableJetifier=false

# Corrección de propiedades obsoletas para compatibilidad con AGP 9.0+
android.defaults.buildfeatures.resvalues=false
android.r8.optimizedResourceShrinking=true
android.enableAppCompileTimeRClass=true